### ISSUE TITLE
弹性布局

### ISSUE THREAD

**Issue by Number314225** [Number314225/Blog#1]
该文章为英文原文译文及一些自己的拙见  
墙裂推荐读原文  
浏览原文请戳这里 : [CSS-STRICKS]  

##### 什么是弹性布局

Flexbox Layout 模块旨在提供一种更为有效的方式来对容器(container)中的每一项(item)进行布置、对齐和空间分配，即使是在其尺寸未知或动态变化的情况下也能很好的发挥作用。

弹性布局的主要思想是赋予容器(container)改变内部每一项的长宽来更好的适应各种尺寸的屏幕(手机、平板或是台式显示器)。一个设置了flex属性的容器(container)可以对其内部的项(item)进行扩大来更好填充可用空间，或是缩小防止溢出。

重要的是，一般布局指基于垂直的块元素(block)和基于水平的行内元素(inline)，弹性布局与一般布局不同的是它与方向无关。虽然一般布局也能很好地规划页面，但它缺乏在页面或元素发生旋转、改变大小时的灵活性。

##### 容器和内部项的属性

弹性布局实为一种模型而非一个属性，其中包含了容器的属性和容器中每一项的属性。

下图阐释了弹性布局的主要思想

![alt](https://raw.githubusercontent.com/Number314225/Blog/master/HTML/Flexbox_Layout/imgs/flexbox.png)

在弹性布局中，容器内部的项(item)的布置方式基于主轴(main axis)或是交叉轴(cross axis)其中之一。

|名称 |备注 |
|-------- |-------- |
|主轴(main axis) |主轴是内部项在布局是最主要遵循的轴，**不一定是水平方向**，其方向基于属性flex-direction的值|
|主轴起始点(main start) |在容器内布局的项从起始点开始|
|主轴结束点(main end) |截止到结束点|
|主轴尺寸(main size) |如图|
|交叉轴(cross axis) |始终保持与主轴垂直，**即不一定是竖直方向**|
|交叉轴起始点(cross start) |内部项在交叉轴上排列的起点|
|交叉轴结束点(cross end) |和终点|
|交叉轴尺寸(cross size) |如图|

## 弹性布局的属性

弹性布局的属性分为容器的属性，和其内部每一项的属性。

在想要使用弹性布局的元素上加上如下代码
```CSS
.container{
	display: flex;	/* 或者 inline-flex */
}
```
此时，```container```元素的```float```、```clear```和```vertical-align```属性将失效。

### 容器的属性

+ **flex-direction**
    ```CSS
    .container {
		flex-direction: row | row-reverse | column | column-reverse;
	}
    ```
    即内部项的排列方向，```flex-direction``` 设置为 ```row-reverse``` 则会从一行的靠右边开始布置，而非是靠左布置。  
    ![alt](https://raw.githubusercontent.com/Number314225/Blog/master/HTML/Flexbox_Layout/imgs/flex-direction2.png)

  |值 |解释 |
  |-------- |-------- |
  |**row(默认)** |在设置了```direction:ltr```的元素上从左到右排列，在设置了```direction:rtl```元素上从右到左排列 |
  |row-reverse |在设置了```direction:ltr```的元素上从右到左排列，在设置了```direction:rtl```元素上从左到右排列 |
  |column |和```row```相同，但从上到下 |
  |column-reverse |和```row-reverse```相同，但从下到上 |

+ **flex-wrap**
    ```CSS
	.container{
		flex-wrap: nowrap | wrap | wrap-reverse;
	}
    ```
    内部项的换行方式。

  |值 |解释 |
  |-------- |:--------:|
  |**nowrap(默认)**	|所有项目排成一行，不换行 |
  |wrap |换行，从上向下排 |
  |wrap-reverse |换行，从下向上排 |

+ **flex-flow**
    ```CSS
	.container{
		flex-flow: <‘flex-direction’> || <‘flex-wrap’>;
	}
    ```
    属性```flex-direction```和```flex-wrap```的简写整合版。
    ```CSS
	.container{
		flex-flow: row-reverse wrap;
	}
	.container{
		flex-direction: row-reverse;
		flex-wrap: nowrap;
	}
	// 两者写法效果等同
    ```
    **默认值为两者的默认值，即 row nowrap**

+ **justify-content**
    ```CSS
	.container {
		justify-content: flex-start | flex-end | center | space-between | space-around | space-evenly;
	}
    ```
    内部项在沿着主轴方向上的对齐方式和间距。  
    ![alt](https://raw.githubusercontent.com/Number314225/Blog/master/HTML/Flexbox_Layout/imgs/justify-content-2.png)

+ **align-items**
    ```CSS
	.container {
		align-items: flex-start | flex-end | center | baseline | stretch;
	}
    ```
    内部项在沿着交叉轴方向上的对齐方式。  
    ![alt](https://raw.githubusercontent.com/Number314225/Blog/master/HTML/Flexbox_Layout/imgs/align-items.png)

+ **align-content**
    ```CSS
	.container {
		align-content: flex-start | flex-end | center | space-between | space-around | stretch;
    ```
    该属性定义了多行情况下，沿交叉轴方向有剩余空间时，各行空间的分配情况，就如同竖直版的```justify-content```属性。  
    ![alt](https://raw.githubusercontent.com/Number314225/Blog/master/HTML/Flexbox_Layout/imgs/align-content.png)

### 内部项的属性

容器子元素所拥有的属性，可以通过对单一子元素修改这些属性达到只改变某一个子元素的布局方式。

+ **order**
    ```CSS
	.item {
		order: <integer>; /* default is 0 */
	}
    ```
    **默认值为0**
    通过比较order属性值的大小来控制那个元素先出现。
    ![alt](https://raw.githubusercontent.com/Number314225/Blog/master/HTML/Flexbox_Layout/imgs/order-2.png)

+ **flex-grow**
    ```CSS
	.item {
		flex-grow: <number>; /* default 0 */
	}
    ```
    **默认值为0。**
    该属性接受一个正数，其指定了某一项在容器内部所占的可用空间的比例大小。
    若所有内部项设置该属性的值为1，容器内不得可用空间会均分给每一个内部项；若有一个内部项设置为2，这个内部项得到的空间将会是其他项的两倍。
    ![alt](https://raw.githubusercontent.com/Number314225/Blog/master/HTML/Flexbox_Layout/imgs/flex-grow.png)

+ **flex-shrink**
    ```CSS
	.item {
		flex-shrink: <number>; /* default 1 */
	}
    ```
    **默认值为1。**
    该属性定义了某一项的缩小。**不能赋予负值。**

+ **flex-basis**
    ```CSS
	.item {
		flex-basis: <length> | auto; /* default auto */
	}
    ```
    该属性定义了在分配可用空间之前，内部项的默认尺寸。
    该属性课赋予长度(如百分比20%，5rem，等)或一个关键字。
    ```auto``` 根据宽高属性值分配空间。
    ```content``` 根据内容多少分配空间。

+ **flex**
    ```CSS
	.item {
		flex: none | [ <'flex-grow'> <'flex-shrink'>? || <'flex-basis'> ]
	}
    ```
    属性```flex-grow```、```flex-shrink```和```flex-basis```的简写整合版，第二第三个参数可选。  
    **默认值为0 1 auto**  
    **推荐使用这种方法代替单独写三个属性分别赋值的写法**

+ **align-self**
    ```CSS
	.item {
		align-self: auto | flex-start | flex-end | center | baseline | stretch;
	}
    ```
    这个属性提供了单独修改某一个项的布局方式(~~也就是说这个方法可以让我们中出一个叛徒~~)，用这个方法所赋予的值将重写该项通过容器属性```align-items```所获得的值。
    
    ![alt](https://raw.githubusercontent.com/Number314225/Blog/master/HTML/Flexbox_Layout/imgs/align-self.png)

## 举些栗子

[CSS-STRICKS]:<https://css-tricks.com/snippets/css/a-guide-to-flexbox/#article-header-id-2>
